### ISSUE TITLE
bug in flgamma-pdf

### ISSUE THREAD

**Issue by rmculpepper** [racket/math#2] opened 2015-03-19 16:38 UTC
There seems to be a problem in `flgamma-pdf`:

```
> (flgamma-pdf 20.0 0.5 400.0 #t)
-711.639114180949
> (flgamma-pdf 20.0 0.5 450.0 #t)
-809.4012365034777
```

but

```
> (flgamma-pdf 20.0 0.5 420.0 #t)
-inf.0
```

**Comment by soegaard** [comment] 2018-05-13 17:11
@ntoronto ping

**Comment by bdeket** [comment] 2019-07-05 01:14
![image](https://user-images.githubusercontent.com/6235541/60691672-c0b5bc80-9ed1-11e9-9a2f-dcc18741c773.png)
The problem is in math/private/distributions/impl/poisson-pdf.rkt
(flgamma-pdf (+ k 1) s (* s l) #t) eventually calls (flpoisson-log-pdf l k) (840 19 in the problematic case)
above the lower black curve flpoisson-log-pdf calls flpoisson-pdf, but there is a triangle were
for k=2->50 and l=760->940 this returns 0.0 (below horizontal black line) and so the log returns -inf.0

Shifting the bound from[ (- l k) < (* 29 (sqrt l)) ](https://github.com/bdeket/math/blob/bbaa2791af866d7d01bb08f25eb4e569b53da414/math-lib/math/private/distributions/impl/poisson-pdf.rkt#L115)to (* 27.2 (sqrt l)) eliminates this triangle but I have no idea if this has other consequences...
In the figure above flpoisson-log-pdf+ is changed to not use the call to flpoisson-pdf


also the case before checks k < 2 and this case checks k > 2 making it so that for k=2 this error doesn't show up...

**Comment by soegaard** [comment] 2019-08-14 20:23
I have commited @bdeket fix in #26.

Is this issue fixed as well?  @rmculpepper

**Comment by bdeket** [comment] 2019-08-15 05:28
sorry to jump in, but yes this was the original idea for this PR

```racket
> (flgamma-pdf 20.0 0.5 400.0 #t)
  (flgamma-pdf 20.0 0.5 420.0 #t) 
  (flgamma-pdf 20.0 0.5 450.0 #t) 
-711.639114180949
-750.7121010617298
-809.4012365034777
```

**Comment by spdegabrielle** [comment] 2020-06-18 09:46
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)

**Comment by soegaard** [comment] 2020-07-04 12:41
I tested the original example from @rmculpepper and that is fixed,
so I am closing this.

Thanks @bdeket

**Closed by soegaard** 2020-07-04 12:41 UTC
Labels: bug, good first issue, help wanted
